apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: helm-app
  namespace: argo-cd
spec: 
  destination: 
    namespace: helm1
    server: "https://kubernetes.default.svc"
  project: helm
  source: 
    path: helm-application
    repoURL: "https://github.com/Shobhit29/argocd-learning"
    targetRevision: main
    helm:
      releaseName: test
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  